"""
Django settings for farmer_project project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

import os
import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from django.utils.translation import gettext_lazy as _

BASE_DIR = Path(__file__).resolve().parent.parent

# Load local .env when present (non-fatal in production containers).
try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / '.env')
except Exception:
    pass

try:
    import whitenoise  # noqa: F401
    HAS_WHITENOISE = True
except Exception:
    HAS_WHITENOISE = False


def env_bool(name, default=False):
    return os.getenv(name, str(default)).strip().lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default=''):
    raw = os.getenv(name, default)
    return [item.strip() for item in raw.split(',') if item.strip()]


def env_int(name, default):
    raw = os.getenv(name, str(default)).strip()
    try:
        return int(raw)
    except ValueError as exc:
        raise ImproperlyConfigured(f"{name} must be an integer. Got: {raw!r}") from exc


IS_TEST = 'test' in sys.argv
DJANGO_ENV = os.getenv('DJANGO_ENV', 'development').strip().lower()
if DJANGO_ENV not in {'development', 'staging', 'production', 'test'}:
    raise ImproperlyConfigured("DJANGO_ENV must be one of development/staging/production/test.")

DEBUG = env_bool('DJANGO_DEBUG', IS_TEST or DJANGO_ENV == 'test')
if DJANGO_ENV in {'staging', 'production'} and DEBUG:
    raise ImproperlyConfigured('DJANGO_DEBUG cannot be enabled in staging/production.')

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    allow_insecure = env_bool('DJANGO_ALLOW_INSECURE_DEV_KEY', False)
    safe_commands = {'test', 'makemigrations', 'migrate', 'check'}
    if IS_TEST or allow_insecure:
        SECRET_KEY = 'django-insecure-dev-key-change-me'
    elif DEBUG and any(cmd in sys.argv for cmd in safe_commands):
        # Optional convenience for local checks when DJANGO_DEBUG=true.
        SECRET_KEY = 'django-insecure-dev-key-change-me'
    else:
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY must be set. For local-only development, set DJANGO_ALLOW_INSECURE_DEV_KEY=true.'
        )

# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', '' if not DEBUG else '127.0.0.1,localhost')
if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured('DJANGO_ALLOWED_HOSTS must be configured when DJANGO_DEBUG is false.')

if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


default_db_engine = 'django.db.backends.sqlite3'
default_db_name = str(BASE_DIR / 'db.sqlite3')
db_engine = os.getenv('DJANGO_DB_ENGINE', default_db_engine)
db_name = os.getenv('DJANGO_DB_NAME', default_db_name)

# Single centralized database definition shared by every role/workflow.
DATABASES = {
    'default': {
        'ENGINE': db_engine,
        'NAME': db_name,
        'USER': os.getenv('DJANGO_DB_USER', ''),
        'PASSWORD': os.getenv('DJANGO_DB_PASSWORD', ''),
        'HOST': os.getenv('DJANGO_DB_HOST', ''),
        'PORT': os.getenv('DJANGO_DB_PORT', ''),
        'CONN_MAX_AGE': env_int('DJANGO_DB_CONN_MAX_AGE', 60),
    }
}

if DJANGO_ENV in {'staging', 'production'} and db_engine == default_db_engine:
    raise ImproperlyConfigured('Staging/production deployments must set non-SQLite database settings.')

CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS')

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'kisan1.apps.Kisan1Config',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'kisan1.middleware.GlobalExceptionMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'kisan1.middleware.SessionSecurityMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'kisan1.middleware.RequestAuditMiddleware',
]
if HAS_WHITENOISE:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'farmer_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'farmer_project.wsgi.application'


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
    {'NAME': 'kisan1.validators.PasswordComplexityValidator',},
]

LANGUAGE_CODE = 'en'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

LANGUAGES = [
    ('en', _('English')),
    ('te', _('Telugu')),
    ('hi', _('Hindi')),
]
LOCALE_PATHS = [BASE_DIR / 'locale']

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'kisan1' / 'static']
if HAS_WHITENOISE:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 1200
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS')

SECURE_HSTS_SECONDS = env_int('DJANGO_SECURE_HSTS_SECONDS', 31536000 if not DEBUG else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', not DEBUG)
SECURE_HSTS_PRELOAD = env_bool('DJANGO_SECURE_HSTS_PRELOAD', not DEBUG)
SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', not DEBUG)
SESSION_COOKIE_SECURE = env_bool('DJANGO_SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = env_bool('DJANGO_CSRF_COOKIE_SECURE', not DEBUG)
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'same-origin'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'kisan1-default-cache',
        'TIMEOUT': 300,
    }
}

LOG_LEVEL = os.getenv('DJANGO_LOG_LEVEL', 'INFO').upper()
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'stream': sys.stdout,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },

    'loggers': {
        'kisan1': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}
if LOG_LEVEL not in {'DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'}:
    raise ImproperlyConfigured('DJANGO_LOG_LEVEL must be one of DEBUG/INFO/WARNING/ERROR/CRITICAL')

OTP_REQUEST_LIMIT = int(os.getenv('OTP_REQUEST_LIMIT', '5'))
OTP_REQUEST_WINDOW_SECONDS = int(os.getenv('OTP_REQUEST_WINDOW_SECONDS', '300'))
OTP_TTL_SECONDS = int(os.getenv('OTP_TTL_SECONDS', '300'))
OTP_ATTEMPT_LIMIT = int(os.getenv('OTP_ATTEMPT_LIMIT', '5'))
LOGIN_ATTEMPT_LIMIT = int(os.getenv('LOGIN_ATTEMPT_LIMIT', '5'))
LOGIN_ATTEMPT_WINDOW_SECONDS = int(os.getenv('LOGIN_ATTEMPT_WINDOW_SECONDS', '900'))
