# Generated by Django 5.2.12 on 2026-03-16 04:46

import django.db.models.deletion
from django.db import migrations, models


def seed_location_records(apps, schema_editor):
    Location = apps.get_model('kisan1', 'Location')
    PincodeMapping = apps.get_model('kisan1', 'PincodeMapping')
    rows = [
        {'pincode': '503306', 'district': 'Kamareddy', 'mandal': 'Bichkunda', 'village': 'Bichkunda'},
        {'pincode': '502286', 'district': 'Sangareddy', 'mandal': 'Kangti', 'village': 'Borgi'},
    ]
    for row in rows:
        Location.objects.get_or_create(**row)
        PincodeMapping.objects.get_or_create(state='Telangana', **row)


class Migration(migrations.Migration):

    dependencies = [
        ("kisan1", "0007_userregistration_kisan1_user_mobile_cc442b_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="pesticideprofile",
            name="service_rate",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userregistration",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userregistration",
            name="pincode",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="userregistration",
            name="service_status",
            field=models.CharField(default="Active", max_length=20),
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pincode", models.CharField(db_index=True, max_length=6)),
                ("district", models.CharField(max_length=100)),
                ("mandal", models.CharField(max_length=100)),
                ("village", models.CharField(max_length=100)),
            ],
            options={
                "unique_together": {("pincode", "district", "mandal", "village")},
            },
        ),
        migrations.AddField(
            model_name="userregistration",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="kisan1.location",
            ),
        ),
        migrations.RunPython(seed_location_records, migrations.RunPython.noop),
    ]
