# Generated by Django 6.0.3 on 2026-03-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kisan1", "0009_sanitize_currency_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="pesticideinventory",
            name="market_price",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
