# Generated by Django 6.0.3 on 2026-03-17 05:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models




def populate_user_identities(apps, schema_editor):
    UserRegistration = apps.get_model("kisan1", "UserRegistration")
    UserIdentity = apps.get_model("kisan1", "UserIdentity")

    for user in UserRegistration.objects.all().iterator():
        identity, _ = UserIdentity.objects.get_or_create(mobile=user.mobile)
        if user.identity_id != identity.id:
            user.identity_id = identity.id
            user.save(update_fields=["identity"])


def clear_user_identities(apps, schema_editor):
    UserRegistration = apps.get_model("kisan1", "UserRegistration")
    UserRegistration.objects.update(identity=None)


class Migration(migrations.Migration):

    dependencies = [
        ("kisan1", "0010_pesticideinventory_market_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Mobile number must be a valid 10-digit Indian mobile number.",
                                regex="^[6-9][0-9]{9}$",
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="userregistration",
            name="mobile",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Mobile number must be a valid 10-digit Indian mobile number.",
                        regex="^[6-9][0-9]{9}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="userregistration",
            name="identity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="kisan1.useridentity",
            ),
        ),
        migrations.RunPython(populate_user_identities, clear_user_identities),
    ]
