# Generated by Django 6.0.3 on 2026-03-24 07:15

import re
import django.db.models.deletion
from django.db import migrations, models


TOOL_RATE_PATTERN = re.compile(
    r'(?P<tool>.+?)\s*\(\s*Rs\.?\s*(?P<rate>\d+)\s*/\s*(?P<unit>hr|day)\s*\)',
    re.IGNORECASE,
)


def seed_tool_inventory(apps, schema_editor):
    ToolsProfile = apps.get_model('kisan1', 'ToolsProfile')
    ToolInventory = apps.get_model('kisan1', 'ToolInventory')

    for profile in ToolsProfile.objects.exclude(tools_type__isnull=True).exclude(tools_type=''):
        for raw_item in profile.tools_type.split('|'):
            cleaned = ' '.join(raw_item.strip().split())
            if not cleaned:
                continue

            match = TOOL_RATE_PATTERN.search(cleaned)
            if match:
                tool_name = ' '.join(match.group('tool').strip().split())
                rate = int(match.group('rate'))
                rate_unit = match.group('unit').lower()
            else:
                tool_name = cleaned
                rate = 0
                rate_unit = 'hr'

            ToolInventory.objects.update_or_create(
                owner=profile.user,
                tool_name=tool_name,
                defaults={
                    'rate': rate,
                    'rate_unit': rate_unit,
                    'is_available': True,
                },
            )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('kisan1', '0012_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('rate', models.PositiveIntegerField(default=0)),
                ('rate_unit', models.CharField(choices=[('hr', 'Per Hour'), ('day', 'Per Day')], default='hr', max_length=10)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_inventory', to='kisan1.userregistration')),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'tool_name'], name='kisan1_tool_owner_i_85e7cd_idx'), models.Index(fields=['owner', 'is_available'], name='kisan1_tool_owner_i_969e6a_idx')],
                'unique_together': {('owner', 'tool_name')},
            },
        ),
        migrations.RunPython(seed_tool_inventory, noop_reverse),
    ]
