# Generated by Django 5.2.12 on 2026-03-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kisan1", "0013_toolinventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="pesticideinventory",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
